"""columns update

Revision ID: c416edbd613c
Revises: 9c3d0dc8fb68
Create Date: 2022-09-11 19:59:17.060441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c416edbd613c'
down_revision = '9c3d0dc8fb68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('zodiac', sa.String(length=200), nullable=True))
    op.drop_column('card', 'description')
    op.drop_column('card', 'suit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('suit', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('card', sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('card', 'zodiac')
    # ### end Alembic commands ###
